
services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"   # host 3001 → container 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
